Repository atlp-rwanda/eagles-bn-frontend, pull requests merged in 2020-12, with the labels that each got.

#1 chore(react): setup empty project
  .env.example
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/index.js
  webpack.config.js
Labels: chore, ready for review

#5 Setup SASS processing on the client [175226614]
  .babelrc
  .dccache
  package.json
  src/App.css
  src/App.js
  src/App.scss
  webpack.config.js
Labels: ready for review

#8 setup redux
  package.json
  src/App.js
  src/index.js
  src/redux/actions/actions.js
  src/redux/actions/index.js
  src/redux/reducers/counter.js
  src/redux/reducers/index.js
Labels: ready for review

#7 chore(set-jest): add test functionality
  .babelrc
  package.json
  src/components/ErrorBoundary/ErrorBoundary.js
  src/test/errorBoundary.test.js
  src/test/test.test.js
Labels: chore, ready for review

#9 Feature/login 175226620
  .gitignore
  package.json
  public/index.html
  src/App.js
  src/App.scss
  src/components/form/input.js
  src/components/loading/loading.js
  src/components/loading/loading.scss
  src/components/pages/login.js
  src/index.js
  src/pages/auth/login/login.js
  src/pages/auth/login/login.scss
  src/pages/dashboard.js
  src/redux/actions/actions.js
  src/redux/actions/index.js
  src/redux/reducers/counter.js
  src/store/action-types/action-types.js
  src/store/actions/auth.js
  src/store/actions/loading.js
  src/store/reducers/auth.js
  src/store/reducers/index.js
  src/store/reducers/loading.js
Labels: ready for review

#10 feat(signup): register user
  .babelrc
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/ErrorBoundary.js.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/components/ErrorBoundary/ErrorBoundary.js.html
  coverage/lcov-report/components/ErrorBoundary/index.html
  coverage/lcov-report/components/Signup.js.html
  coverage/lcov-report/components/form/index.html
  coverage/lcov-report/components/form/input.js.html
  coverage/lcov-report/components/index.html
  coverage/lcov-report/components/loading/index.html
  coverage/lcov-report/components/loading/loading.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/pages/auth/login/index.html
  coverage/lcov-report/pages/auth/login/login.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/store/action-types/action-types.js.html
  coverage/lcov-report/store/action-types/index.html
  coverage/lcov-report/store/actions/auth.js.html
  coverage/lcov-report/store/actions/index.html
  coverage/lcov-report/store/actions/loading.js.html
  coverage/lcov-report/store/reducers/auth.js.html
  coverage/lcov-report/store/reducers/index.html
  coverage/lcov-report/store/reducers/index.js.html
  coverage/lcov-report/store/reducers/loading.js.html
  coverage/lcov-report/store/signup/actions.js.html
  coverage/lcov-report/store/signup/index.html
  coverage/lcov-report/store/signup/reducer.js.html
  coverage/lcov-report/store/signup/types.js.html
  coverage/lcov-report/test/index.html
  coverage/lcov-report/test/signup-test-utils.js.html
  coverage/lcov.info
  jestconfig.json
  package.json
  src/App.js
  src/App.scss
  src/components/Signup.js
  src/components/signup.scss
  src/index.js
  src/pages/auth/login/login.js
  src/store/reducers/index.js
  src/store/signup/actions.js
  src/store/signup/reducer.js
  src/store/signup/types.js
  src/test/signup-test-utils.js
  src/test/signup.test.js
Labels: WIP, feat

#15 Facebook and Google login implementation
  .gitignore
  __mocks__/fileFormatter.js
  jestconfig.json
  package.json
  src/assets/images/facebook-logo.png
  src/assets/images/google-logo.png
  src/components/Signup.js
  src/components/socialLogin/SocialLogin.js
  src/components/socialLogin/SocialLogin.scss
  src/components/socialLogin/socialView.js
  src/layout/main/Main.js
  src/pages/auth/login/login.js
  src/store/action-types/action-types.js
  src/store/actions/oauth/oauth.js
  src/store/actions/oauth/oauthAction.js
  src/store/reducers/index.js
  src/store/reducers/oauthReducer.js
  webpack.config.js
Labels: ready for review

#16 accommodation view
  debug.log
  package.json
  src/App.js
  src/components/accommodations/Accomodations.js
  src/components/accommodations/SingleAccommodation.js
  src/components/accommodations/accommodationImage.js
  src/components/accommodations/mapStateToProps.js
  src/index.js
  src/layout/components/accommodations/Accommodations.js
  src/layout/components/accommodations/Accommodations.scss
  src/layout/components/accommodations/SingleAccommodation.scss
  src/layout/components/accommodations/ViewServices.scss
  src/layout/components/accommodations/roamHelper.js
  src/layout/components/accommodations/viewRoam.js
  src/layout/components/accommodations/viewServices.js
  src/layout/components/navigation/navigation.js
  src/layout/main/Main.js
  src/pages/dashboard/dashboard.js
  src/store/accommodations/accommodationReducer.js
  src/store/accommodations/fetchAccommodation.js
  src/store/accommodations/initialState.js
  src/store/action-types/action-types.js
  src/store/actions/accommodation.js
  src/store/reducers/index.js
  src/test/accommodations/actions.test.js
  src/test/accommodations/reducer.test.js
Labels: feat, ready for review

#14 feat(trip-status):change trip status
  src/components/Signup.js
  src/components/form/select/select.js
  src/components/signup.scss
  src/pages/Profile.js
  src/pages/requests/requests-table.js
  src/pages/requests/requests.js
  src/pages/requests/tripStatus.js
  src/store/reducers/index.js
  src/store/signup/actions.js
  src/store/tripStatus/actions.js
  src/store/tripStatus/reducer.js
  src/store/tripStatus/types.js
Labels: feat, ready for review
